server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  application:
    name: turno-los
  
  # Database Configuration
  datasource:
    # For development - H2 in-memory database
    url: jdbc:h2:mem:turno_los
    username: sa
    password: 
    driver-class-name: org.h2.Driver
    
    # For production - PostgreSQL
    # url: jdbc:postgresql://localhost:5432/turno_los
    # username: turno_user
    # password: turno_password
    # driver-class-name: org.postgresql.Driver
  
  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: create-drop  # create-drop for development, validate for production
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect  # H2Dialect for development, PostgreSQLDialect for production
        format_sql: true
        use_sql_comments: true
  
  # H2 Console (for development)
  h2:
    console:
      enabled: true
      path: /h2-console
  
  # Jackson Configuration
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false

# Application-specific configuration
los:
  processing:
    thread-pool-size: 5
    delay-min-seconds: 20
    delay-max-seconds: 30
    queue-capacity: 100
  notification:
    enabled: true
    push-notification-enabled: true
    sms-enabled: true

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized
  metrics:
    export:
      prometheus:
        enabled: true

# Logging Configuration
logging:
  level:
    com.turno.los: DEBUG
    org.springframework.scheduling: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# OpenAPI Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
  info:
    title: Turno LOS API
    description: Loan Origination System API Documentation
    version: 1.0.0
    contact:
      name: Turno Development Team
      email: dev@turno.com 